apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ax.fullname" . }}
  labels:
    {{- include "ax.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-conn: {{ include "ax.postgresConnStr" . | quote }}
  {{- if .Values.github.token }}
  gh-token: {{ .Values.github.token | quote }}
  {{- end }}
  {{- if .Values.apiKey }}
  api-key: {{ .Values.apiKey | quote }}
  {{- end }}
