apiVersion: v1
kind: Service
metadata:
  name: {{ include "ax.fullname" . }}-server
  labels:
    {{- include "ax.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.server.port }}
      targetPort: {{ .Values.server.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "ax.name" . }}
    app.kubernetes.io/component: server
