# Code generated by scripts/codegen-agents — DO NOT EDIT.
# Source: config/agents.yaml

module AgentRegistry
  AGENTS = {
    "claude_code" => {
      label: "Claude Code",
      color: "#c4621a",
      home_dir_env: "AX_CLAUDE_HOME",
      home_dir_default: "~/.claude",
      hook_scopes: [ "user" ],
      fields: {
        input_tokens: true,
        output_tokens: true,
        cache_creation_input_tokens: true,
        cache_read_input_tokens: true,
        sidechain_messages: true,
        peak_context_pct: true,
        total_file_reads: true,
        total_tool_calls: true,
        agent_tool_calls: true,
        skill_tool_calls: true,
        mcp_tool_calls: true
      },
      metrics: {
        "iteration-depth" => true,
        "cache-hit-rate" => true,
        "sidechain-rate" => true,
        "peak-context-pct" => true,
        "re-read-rate" => true,
        "autonomy-score" => true,
        "skill-tool-usage" => true,
        "subagent-delegation" => true,
        "token-cost-per-pr" => true
      }
    },
    "copilot_cli" => {
      label: "Copilot CLI",
      color: "#5a8fd8",
      home_dir_env: "COPILOT_HOME",
      home_dir_default: "~/.copilot",
      hook_scopes: [ "repo" ],
      fields: {
        input_tokens: true,
        output_tokens: true,
        cache_creation_input_tokens: true,
        cache_read_input_tokens: true,
        sidechain_messages: false,
        peak_context_pct: false,
        total_file_reads: true,
        total_tool_calls: true,
        agent_tool_calls: true,
        skill_tool_calls: false,
        mcp_tool_calls: true
      },
      metrics: {
        "iteration-depth" => true,
        "cache-hit-rate" => true,
        "sidechain-rate" => false,
        "peak-context-pct" => false,
        "re-read-rate" => true,
        "autonomy-score" => true,
        "skill-tool-usage" => false,
        "subagent-delegation" => true,
        "token-cost-per-pr" => true
      }
    },
    "cursor_cli" => {
      label: "Cursor CLI",
      color: "#5a7a5a",
      home_dir_env: "CURSOR_HOME",
      home_dir_default: "~/.cursor",
      hook_scopes: [ "user", "repo" ],
      fields: {
        input_tokens: false,
        output_tokens: false,
        cache_creation_input_tokens: false,
        cache_read_input_tokens: false,
        sidechain_messages: false,
        peak_context_pct: false,
        total_file_reads: true,
        total_tool_calls: true,
        agent_tool_calls: false,
        skill_tool_calls: false,
        mcp_tool_calls: false
      },
      metrics: {
        "iteration-depth" => true,
        "cache-hit-rate" => false,
        "sidechain-rate" => false,
        "peak-context-pct" => false,
        "re-read-rate" => true,
        "autonomy-score" => true,
        "skill-tool-usage" => false,
        "subagent-delegation" => false,
        "token-cost-per-pr" => false
      }
    }
  }.freeze

  VALID_IDS = AGENTS.keys.freeze

  def self.valid?(id)
    AGENTS.key?(id.to_s)
  end

  def self.supports_field?(id, field)
    !!AGENTS.dig(id.to_s, :fields, field.to_sym)
  end

  def self.supports_metric?(id, slug)
    !!AGENTS.dig(id.to_s, :metrics, slug.to_s)
  end

  def self.metric_supported_by_any?(slug)
    AGENTS.any? { |_, meta| meta[:metrics][slug.to_s] }
  end

  def self.agents_supporting_metric(slug)
    AGENTS.select { |_, meta| meta[:metrics][slug.to_s] }.keys
  end

  def self.label(id)
    AGENTS.dig(id.to_s, :label) || id.to_s
  end

  def self.color(id)
    AGENTS.dig(id.to_s, :color)
  end
end
