// Code generated by scripts/codegen-agents — DO NOT EDIT.
// Source: config/agents.yaml

package agents

// AgentID is the wire-format identifier for an agent.
type AgentID string

const (
	ClaudeCode AgentID = "claude_code"
	CopilotCli AgentID = "copilot_cli"
	CursorCli AgentID = "cursor_cli"
)

// AllAgents is the set of every agent registered in agents.yaml.
var AllAgents = []AgentID{
	"claude_code",
	"copilot_cli",
	"cursor_cli",
}

// Capabilities declares which fields and metrics an agent supplies.
type Capabilities struct {
	Fields  map[string]bool
	Metrics map[string]bool
}

// Metadata is the static, dashboard-relevant info for an agent.
type Metadata struct {
	ID             AgentID
	Label          string
	Color          string   // 7-char hex including #
	HomeDirEnv     string
	HomeDirDefault string
	HookScopes     []string // "user", "repo"
	Capabilities   Capabilities
}

// Registry returns the full agent registry indexed by AgentID.
func Registry() map[AgentID]Metadata {
	return map[AgentID]Metadata{
		"claude_code": {
			ID:             "claude_code",
			Label:          "Claude Code",
			Color:          "#c4621a",
			HomeDirEnv:     "AX_CLAUDE_HOME",
			HomeDirDefault: "~/.claude",
			HookScopes:     []string{"user"},
			Capabilities: Capabilities{
				Fields: map[string]bool{
					"input_tokens": true,
					"output_tokens": true,
					"cache_creation_input_tokens": true,
					"cache_read_input_tokens": true,
					"sidechain_messages": true,
					"peak_context_pct": true,
					"total_file_reads": true,
					"total_tool_calls": true,
					"agent_tool_calls": true,
					"skill_tool_calls": true,
					"mcp_tool_calls": true,
				},
				Metrics: map[string]bool{
					"iteration-depth": true,
					"cache-hit-rate": true,
					"sidechain-rate": true,
					"peak-context-pct": true,
					"re-read-rate": true,
					"autonomy-score": true,
					"skill-tool-usage": true,
					"subagent-delegation": true,
					"token-cost-per-pr": true,
				},
			},
		},
		"copilot_cli": {
			ID:             "copilot_cli",
			Label:          "Copilot CLI",
			Color:          "#5a8fd8",
			HomeDirEnv:     "COPILOT_HOME",
			HomeDirDefault: "~/.copilot",
			HookScopes:     []string{"repo"},
			Capabilities: Capabilities{
				Fields: map[string]bool{
					"input_tokens": true,
					"output_tokens": true,
					"cache_creation_input_tokens": true,
					"cache_read_input_tokens": true,
					"sidechain_messages": false,
					"peak_context_pct": false,
					"total_file_reads": true,
					"total_tool_calls": true,
					"agent_tool_calls": true,
					"skill_tool_calls": false,
					"mcp_tool_calls": true,
				},
				Metrics: map[string]bool{
					"iteration-depth": true,
					"cache-hit-rate": true,
					"sidechain-rate": false,
					"peak-context-pct": false,
					"re-read-rate": true,
					"autonomy-score": true,
					"skill-tool-usage": false,
					"subagent-delegation": true,
					"token-cost-per-pr": true,
				},
			},
		},
		"cursor_cli": {
			ID:             "cursor_cli",
			Label:          "Cursor CLI",
			Color:          "#5a7a5a",
			HomeDirEnv:     "CURSOR_HOME",
			HomeDirDefault: "~/.cursor",
			HookScopes:     []string{"user", "repo"},
			Capabilities: Capabilities{
				Fields: map[string]bool{
					"input_tokens": false,
					"output_tokens": false,
					"cache_creation_input_tokens": false,
					"cache_read_input_tokens": false,
					"sidechain_messages": false,
					"peak_context_pct": false,
					"total_file_reads": true,
					"total_tool_calls": true,
					"agent_tool_calls": false,
					"skill_tool_calls": false,
					"mcp_tool_calls": false,
				},
				Metrics: map[string]bool{
					"iteration-depth": true,
					"cache-hit-rate": false,
					"sidechain-rate": false,
					"peak-context-pct": false,
					"re-read-rate": true,
					"autonomy-score": true,
					"skill-tool-usage": false,
					"subagent-delegation": false,
					"token-cost-per-pr": false,
				},
			},
		},
	}
}

// Valid reports whether id is a known AgentID.
func Valid(id AgentID) bool {
	_, ok := Registry()[id]
	return ok
}
