// Code generated by scripts/codegen-agents — DO NOT EDIT.
// Source: config/agents.yaml

export type AgentType = "claude_code" | "copilot_cli";

export const ALL_AGENTS: readonly AgentType[] = [
  "claude_code",
  "copilot_cli",
] as const;

export const AGENT_LABELS: Record<AgentType, string> = {
  "claude_code": "Claude Code",
  "copilot_cli": "Copilot CLI",
};

export const AGENT_COLORS: Record<AgentType, string> = {
  "claude_code": "#c4621a",
  "copilot_cli": "#5a8fd8",
};

type AgentCapabilities = {
  fields: Record<string, boolean>;
  metrics: Record<string, boolean>;
};

export const AGENT_CAPABILITIES: Record<AgentType, AgentCapabilities> = {
  "claude_code": {
    fields: {
      input_tokens: true,
      output_tokens: true,
      cache_creation_input_tokens: true,
      cache_read_input_tokens: true,
      sidechain_messages: true,
      peak_context_pct: true,
      total_file_reads: true,
      total_tool_calls: true,
      agent_tool_calls: true,
      skill_tool_calls: true,
      mcp_tool_calls: true,
    },
    metrics: {
      "iteration-depth": true,
      "cache-hit-rate": true,
      "sidechain-rate": true,
      "peak-context-pct": true,
      "re-read-rate": true,
      "autonomy-score": true,
      "skill-tool-usage": true,
      "subagent-delegation": true,
      "token-cost-per-pr": true,
    },
  },
  "copilot_cli": {
    fields: {
      input_tokens: true,
      output_tokens: true,
      cache_creation_input_tokens: true,
      cache_read_input_tokens: true,
      sidechain_messages: false,
      peak_context_pct: false,
      total_file_reads: true,
      total_tool_calls: true,
      agent_tool_calls: true,
      skill_tool_calls: false,
      mcp_tool_calls: true,
    },
    metrics: {
      "iteration-depth": true,
      "cache-hit-rate": true,
      "sidechain-rate": false,
      "peak-context-pct": false,
      "re-read-rate": true,
      "autonomy-score": true,
      "skill-tool-usage": false,
      "subagent-delegation": true,
      "token-cost-per-pr": true,
    },
  },
};

export function isAgentType(value: string): value is AgentType {
  return (ALL_AGENTS as readonly string[]).includes(value);
}

export function agentSupportsMetric(id: AgentType, slug: string): boolean {
  return AGENT_CAPABILITIES[id].metrics[slug] ?? false;
}

export function agentsSupportingMetric(slug: string): AgentType[] {
  return ALL_AGENTS.filter((id) => agentSupportsMetric(id, slug));
}

export function metricHasMultipleAgents(slug: string): boolean {
  return agentsSupportingMetric(slug).length > 1;
}
