require "yaml"
require "tmpdir"
require "fileutils"
require "open3"

CODEGEN_DIR = File.expand_path("..", __dir__)
GENERATE_SCRIPT = File.join(CODEGEN_DIR, "generate.rb")
FIXTURES_DIR = File.join(__dir__, "fixtures")
ROOT = File.expand_path("../../", CODEGEN_DIR)

require_relative "../schema"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def valid_yaml_raw
  YAML.safe_load_file(File.join(FIXTURES_DIR, "valid_agents.yaml"))
end

def run_generate(*args, env: {})
  cmd = ["ruby", GENERATE_SCRIPT, *args]
  out, err, status = Open3.capture3(env, *cmd, chdir: ROOT)
  [out, err, status]
end

# ---------------------------------------------------------------------------
# Schema validation
# ---------------------------------------------------------------------------

RSpec.describe Schema do
  describe ".validate!" do
    it "accepts a valid config" do
      expect { Schema.validate!(valid_yaml_raw) }.not_to raise_error
    end

    it "raises on missing schema_version" do
      raw = valid_yaml_raw.tap { |r| r.delete("schema_version") }
      expect { Schema.validate!(raw) }.to raise_error(Schema::Error, /schema_version/)
    end

    it "raises on missing field_keys" do
      raw = valid_yaml_raw.tap { |r| r.delete("field_keys") }
      expect { Schema.validate!(raw) }.to raise_error(Schema::Error, /field_keys/)
    end

    it "raises on missing metric_slugs" do
      raw = valid_yaml_raw.tap { |r| r.delete("metric_slugs") }
      expect { Schema.validate!(raw) }.to raise_error(Schema::Error, /metric_slugs/)
    end

    it "raises on missing agents" do
      raw = valid_yaml_raw.tap { |r| r.delete("agents") }
      expect { Schema.validate!(raw) }.to raise_error(Schema::Error, /agents/)
    end

    it "raises on empty agents hash" do
      raw = valid_yaml_raw
      raw["agents"] = {}
      expect { Schema.validate!(raw) }.to raise_error(Schema::Error, /empty/)
    end

    it "raises on agent id with invalid pattern" do
      raw = valid_yaml_raw
      meta = raw["agents"].values.first.dup
      raw["agents"] = { "BadAgent" => meta }
      expect { Schema.validate!(raw) }.to raise_error(Schema::Error, /lowercase snake_case/)
    end

    it "raises on invalid color format" do
      raw = valid_yaml_raw
      raw["agents"]["claude_code"]["color"] = "red"
      expect { Schema.validate!(raw) }.to raise_error(Schema::Error, /color/)
    end

    it "raises on empty hook_scopes" do
      raw = valid_yaml_raw
      raw["agents"]["claude_code"]["hook_scopes"] = []
      expect { Schema.validate!(raw) }.to raise_error(Schema::Error, /hook_scopes/)
    end

    it "raises on unknown hook_scope value" do
      raw = valid_yaml_raw
      raw["agents"]["claude_code"]["hook_scopes"] = ["global"]
      expect { Schema.validate!(raw) }.to raise_error(Schema::Error, /hook_scopes/)
    end

    it "raises on missing field key" do
      raw = valid_yaml_raw
      raw["agents"]["claude_code"]["fields"].delete("input_tokens")
      expect { Schema.validate!(raw) }.to raise_error(Schema::Error, /missing keys/)
    end

    it "raises on unknown field key" do
      raw = valid_yaml_raw
      raw["agents"]["claude_code"]["fields"]["unknown_field"] = true
      expect { Schema.validate!(raw) }.to raise_error(Schema::Error, /unknown keys/)
    end

    it "raises on missing metric slug" do
      raw = valid_yaml_raw
      raw["agents"]["claude_code"]["metrics"].delete("iteration-depth")
      expect { Schema.validate!(raw) }.to raise_error(Schema::Error, /missing slugs/)
    end

    it "raises on unknown metric slug" do
      raw = valid_yaml_raw
      raw["agents"]["claude_code"]["metrics"]["nonexistent-metric"] = true
      expect { Schema.validate!(raw) }.to raise_error(Schema::Error, /unknown slugs/)
    end

    it "raises on non-boolean field value" do
      raw = valid_yaml_raw
      raw["agents"]["claude_code"]["fields"]["input_tokens"] = "yes"
      expect { Schema.validate!(raw) }.to raise_error(Schema::Error, /true or false/)
    end
  end
end

# ---------------------------------------------------------------------------
# Golden-file rendering
# ---------------------------------------------------------------------------

RSpec.describe "generate.rb golden-file rendering" do
  let(:generated_go) { File.read(File.join(ROOT, "cli/internal/agents/registry.gen.go")) }
  let(:generated_rb) { File.read(File.join(ROOT, "server/app/models/agent_registry.rb")) }
  let(:generated_ts) { File.read(File.join(ROOT, "dashboard/src/lib/agents.gen.ts")) }
  let(:generated_txt) { File.read(File.join(ROOT, "server/db/agent_types.txt")) }

  it "generates Go file with correct header" do
    expect(generated_go).to start_with("// Code generated by scripts/codegen-agents — DO NOT EDIT.")
  end

  it "generates Go file with AgentID type" do
    expect(generated_go).to include("type AgentID string")
  end

  it "generates Go consts for each agent" do
    expect(generated_go).to include('ClaudeCode AgentID = "claude_code"')
  end

  it "generates Go Registry() function" do
    expect(generated_go).to include("func Registry() map[AgentID]Metadata {")
  end

  it "generates Ruby file with correct header" do
    expect(generated_rb).to start_with("# Code generated by scripts/codegen-agents — DO NOT EDIT.")
  end

  it "generates Ruby VALID_IDS constant" do
    expect(generated_rb).to include("VALID_IDS = AGENTS.keys.freeze")
  end

  it "generates Ruby supports_field? method" do
    expect(generated_rb).to include("def self.supports_field?(id, field)")
  end

  it "generates TypeScript file with correct header" do
    expect(generated_ts).to start_with("// Code generated by scripts/codegen-agents — DO NOT EDIT.")
  end

  it "generates TypeScript AgentType union" do
    expect(generated_ts).to include('export type AgentType = "claude_code" | "copilot_cli"')
  end

  it "generates TypeScript ALL_AGENTS constant" do
    expect(generated_ts).to include("export const ALL_AGENTS: readonly AgentType[]")
  end

  it "generates TypeScript isAgentType function" do
    expect(generated_ts).to include("export function isAgentType(value: string): value is AgentType")
  end

  it "generates agent_types.txt with one agent per line" do
    lines = generated_txt.lines.map(&:chomp).reject(&:empty?)
    expect(lines).to eq(["claude_code", "copilot_cli"])
  end

  it "generates Ruby file that parses without syntax error" do
    _, err, status = Open3.capture3("ruby", "-c", File.join(ROOT, "server/app/models/agent_registry.rb"))
    expect(status.success?).to be(true), "ruby -c failed: #{err}"
  end
end

# ---------------------------------------------------------------------------
# --check mode
# ---------------------------------------------------------------------------

RSpec.describe "generate.rb --check mode" do
  it "exits 0 when generated files are in sync" do
    _, err, status = run_generate("--check")
    expect(status.exitstatus).to eq(0), "expected exit 0 but got #{status.exitstatus}: #{err}"
  end

  it "exits 1 and reports drift when a generated file is stale" do
    Dir.mktmpdir do |tmpdir|
      # Copy root to a temp location and corrupt one generated file
      fake_root = File.join(tmpdir, "ax")
      FileUtils.cp_r(ROOT, fake_root)

      go_file = File.join(fake_root, "cli/internal/agents/registry.gen.go")
      File.write(go_file, "// stale content\n")

      _, err, status = Open3.capture3(
        "ruby", File.join(fake_root, "scripts/codegen-agents/generate.rb"), "--check",
        chdir: fake_root
      )
      expect(status.exitstatus).to eq(1), "expected exit 1 but got #{status.exitstatus}"
      expect(err).to include("cli/internal/agents/registry.gen.go")
    end
  end
end
